spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spring
    password: spring
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh