server:
  port: 8763 # 通过改变端口重新启动一个实例的时候会发现服务中心有 service-hi 的 Availability Zones 会变为 2 此时相当于集群

spring:
  application:
    name: service-hi # 服务与服务之间相互调用一般都是根据这个name
  zipkin:
    base-url: http://localhost:9411 # 链路追踪服务的地址
    sender:
      type: web # 配置 zipkin 的通讯方式
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # 注册中心的地址